apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: esp-ingress
  annotations:
    # This annotation will tell Kubernetes not to create a Google Cloud Load Balancer and to use our NGINX ingress controller instead.
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    type: endpoints-app
spec:
  rules:
  - host: api.endpoints.[MY_PROJECT_ID].cloud.goog
    http:
      paths:
      - backend:
          serviceName: esp-srv
          servicePort: 80
