apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
        track: stable
    spec:
      containers:
        - name: db
          image: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: a12345
          ports:
            - name: mariadb
              containerPort: 3306
#          volumeMounts:
#            - name: db-persistent-storage
#              mountPath: /var/db
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
#      volumes:
#        - name: db-persistent-storage
#          persistentVolumeClaim:
#            claimName: "tls-certs"