# This is the only manifest in the project. It sets up a single pod with 1 replica.
# That pod contains two containers, phpMyAdmin and Cloud SQL Proxy.
# Both containers rely on the GKE secrets that were added as part of the creation scripts.
# There is no Service because we are using a very simple port-forward to access the pod.

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      volumes:
        # If you made a secret as a file you can create a volume from it
        - name: proxy-sa-creds
          secret:
            secretName: proxy-sa-creds
      containers:
          # This is the official phpMyAdmin container
        - image: phpmyadmin/phpmyadmin
          name: phpmyadmin
          # You can make environment variables from GKE secrets
          # You can read them directly using 'secretKeyRef'
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secret
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secret
                  key: password
            - name: PMA_HOST
              value: '127.0.0.1'
            - name: PMA_PORT
              value: '5432'
          ports:
            - containerPort: 80
              name: phpmyadmin
        # We are pulling the Cloud SQL Proxy container from the official Google
        # container repository
        - image: gcr.io/cloudsql-docker/gce-proxy:1.11
          name: cloudsql-proxy
          # You can make environment variables from GKE configurations
          # You can read them from a configmap directly with configMapKeyRef
          env:
            - name: INSTANCE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: connectionname
                  key: connectionname
          command: [
            "/cloud_sql_proxy",
            "-instances=$(INSTANCE_CONNECTION)=tcp:5432",
            # We are accessing the secret file inside the volume.
            # In most circumstances you would use environment variables but
            # the Cloud SQL Proxy container wants a file so we give it one
            "-credential_file=/secrets/cloudsql/credentials.json"
          ]
          # Once the volume is made earlier in the file you then mount the
          # volume so you can access the secret file inside it
          volumeMounts:
            - name: proxy-sa-creds
              mountPath: /secrets/cloudsql
              readOnly: true