apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-www
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: www
        track: stable
        version: 1.0.0
    spec:
      containers:
        - name: www
          image: asia.gcr.io/tekapocart/www:1.0.0
          env:
            - name: TC_DOMAIN
              value: k8s.tekapo.space
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 81
#              scheme: HTTP
#            initialDelaySeconds: 5
#            periodSeconds: 15
#            timeoutSeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /readiness
#              port: 81
#              scheme: HTTP
#            initialDelaySeconds: 5
#            timeoutSeconds: 1