apiVersion: v1
kind: Pod
metadata:
  name: pod-www
  labels:
    app: www
spec:
  containers:
    - name: www
      image: asia.gcr.io/tekapocart/www:1.0.0
#      args:
#        - "-http=0.0.0.0:80"
#        - "-health=0.0.0.0:81"
#        - "-secret=secret"
      ports:
        - name: http
          containerPort: 80
#        - name: health
#          containerPort: 81
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"